### ISSUE TITLE
Запуск с трудом

### ISSUE THREAD

**Issue by ghost** [Boolive/Boolive#117]
Проект запустился с трудом... Установщик не сработал!

**Comment by VladimirShestakov** [comment]
Измени в config.php  IS_INSTALL на false

**Comment by ghost** [comment]
![gph](https://f.cloud.github.com/assets/4105730/363183/20ba802c-a1fc-11e2-862b-d91a3ab6bb84.jpg)

После немногих танцев с бубном заработало!

**Comment by ghost** [comment]
Устанавливал вручную! в папке setup sql запросы нашел, установил, конфиги пробил.
Почему дефайн директива установки стоит в true?

**Comment by VladimirShestakov** [comment]
Не нужно было вручную. дамп базы старый. Измени константу, чтоб запустился установщик. Установщик не использует дамп

**Comment by ghost** [comment]
Чтобы не копаться в Вашей ЦМС, вопрос на засыпку! Админка есть? Похоже, что нет..

**Comment by VladimirShestakov** [comment]
Админка есть по адресу /admin

**Comment by ghost** [comment]
Ничего похожего на админку не отображается по адресу /admin, обычная страница похожая га главную!

**Comment by ghost** [comment]
Установка по дефолту была очень-очень долгой и нудной!

**Comment by VladimirShestakov** [comment]
Показывать анекдоты или мультик во время установки?
Что работает? Сделайте дамп базы, прикрепите сюда, изучим.

**Comment by VladimirShestakov** [comment]
Вы столкнулись с проблемами из-за установки движка в поддиректорию, что ещё не было протестировано.
Работа в поддиректории исправлена. Обновитесь. Для установки измените в config.php константу IS_INSTALL на false. Если устанавливаете в поддиректорию, то в .htaccess отключите mod_rewrite: `RewriteEngine Off`. После установки всё включится, отобразится главная страница с текстом и будет доступна админка без пароля по адресу /admin

**Comment by ghost** [comment]
> > > Показывать анекдоты или мультик во время установки?
> > > А почему бы нет? С такой долгой установкой можно заснуть... Берите практику с Гугл+, они создают при долгих загрузках чего-то какой-нить веселый текст, анимацию. Это поможет и Вашей ЦМС избежать потери пользователей на столь раннем этапе использования ЦМС - "установке"! :)

**Comment by JialuZhang** [comment]
@VladimirShestakov 

In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
